services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: carbigdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: carbigdata
      DB_USER: postgres
      DB_PASSWORD: postgres
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USER: admin
      MINIO_PASSWORD: admin123
      MINIO_BUCKET: fotos
      JWT_SECRET: kPZc5YyJkHz2AxuNq3LxRvqGnJqM9sB0dXjHg7qF9C
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  minio_data: