spring:
  application:
    name: carbigdata-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:carbigdata}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  project:
    app:
      jwtSecret: ${JWT_SECRET:-kPZc5YyJkHz2AxuNq3LxRvqGnJqM9sB0dXjHg7qF9CM=}
      jwtExpirationMs: ${JWT_EXPIRATION:-1800000}

minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_USER:admin}
  secret-key: ${MINIO_PASSWORD:admin123}
  bucket: ${MINIO_BUCKET:fotos}
