spring:
  docker:
    compose:
      enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10

  flyway:
    enabled: false

project:
  app:
    jwtSecret: ${JWT_SECRET:kPZc5YyJkHz2AxuNq3LxRvqGnJqM9sB0dXjHg7qF9CM=}
    jwtExpirationMs: 600000000000

server:
  port: 8081

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket: fotos

logging:
  level:
    root: INFO
    com.carbigdata_api: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE